Minor Fixes and added window to edit lightmap settings for h2codez
num0005/Osoyoos-Launcher pull request #1
Opened 2021-05-08 21:19 UTC by Berthalamew

2021-05-08 21:24 UTC, num0005 commented
CC @General-101 for the changes to the profile wizard.

2021-05-08 21:25 UTC, num0005 commented
Could you provide some screenshots showing how you adjusted the "about" dialogue and what the new one looks like?

2021-05-08 21:31 UTC, Berthalamew commented
![image](https://user-images.githubusercontent.com/40469582/117554031-15bd3f00-b023-11eb-89e1-3e41540a35ba.PNG)
I just extended the size of the window so you didn't have to scroll down to see the last two lines

2021-05-08 21:31 UTC, num0005 requested changes

2021-05-08 21:31 UTC, num0005 commented on Launcher/EditLightmapSettings.xaml.cs
> +
You shouldn't be doing this. For a start the H1toolkit is unused, secondly while this works right now it's fragile. Please get the path when creating the dialog instead of like this.

2021-05-08 21:31 UTC, num0005 commented on Launcher/EditLightmapSettings.xaml.cs
> +
Why do you write a file to disk without user confirmation and then read it right back? Also would be best to have the read/write code for the config in it's own class.

2021-05-08 21:35 UTC, Berthalamew commented on Launcher/EditLightmapSettings.xaml.cs
> +
Write a file since if the file doesn't exist in the directory I create one to avoid a crash and then read back the data so I can display the data of the file in the text and checkboxes.

2021-05-08 22:10 UTC, General-101 requested changes

2021-05-09 16:53 UTC, Berthalamew commented on Launcher/EditLightmapSettings.xaml.cs
> +
https://github.com/num0005/Osoyoos-Launcher/blob/e0cc034d7b6df4a41b5b53fe8ed81a5a6cec3145/Launcher/EditLightmapSettings.xaml.cs#L14

Fixed in latest commit

2021-05-09 16:54 UTC, Berthalamew commented on Launcher/EditLightmapSettings.xaml.cs
> +
https://github.com/num0005/Osoyoos-Launcher/blob/e0cc034d7b6df4a41b5b53fe8ed81a5a6cec3145/Launcher/EditLightmapSettings.xaml.cs#L17
https://github.com/num0005/Osoyoos-Launcher/blob/e0cc034d7b6df4a41b5b53fe8ed81a5a6cec3145/Launcher/EditLightmapSettings.xaml.cs#L30

Moved text that's printed out as it's own class and added function to write out the file

2021-05-09 16:56 UTC, Berthalamew commented on Launcher/Credits.xaml
> +        Title="Credits" Height="405" ResizeMode="NoResize" SizeToContent="Width" d:DesignWidth="451.35">
https://github.com/num0005/Osoyoos-Launcher/blob/e0cc034d7b6df4a41b5b53fe8ed81a5a6cec3145/Launcher/Credits.xaml#L8

Fixed so SizeToContent is used both for width and height.

2021-05-09 16:58 UTC, Berthalamew commented on Launcher/PathSettings.xaml.cs
> +            //Check to see if path for directory is empty to prevent crash in profile wizard
https://github.com/num0005/Osoyoos-Launcher/blob/e0cc034d7b6df4a41b5b53fe8ed81a5a6cec3145/Launcher/PathSettings.xaml.cs#L145

Checking if it's empty now before CreateProfileTemplate is called.

2021-05-12 15:37 UTC, closed without merging