Auto FBX
num0005/Osoyoos-Launcher pull request #20
Opened 2022-01-06 03:57 UTC by infernoplus

Let me know if I should adjust anything. A bit messy.

Adding support for H1/H2 should be a real easy copy paste job but I need to know the folder structure and commands for each game.

2022-01-06 04:27 UTC, num0005 requested changes
Overall it's a nice feature and would be great to support it for all toolkits.

I think you could move the implementation to a separate static class or something like that and use the interfaces setup for FBX to make it work for all games. Maybe there is a more natural way to do that in C# just the best thing I can think of right now. Really wish C# had multiple inheritance.

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H1AToolkit.cs
> +        public override async Task ImportModel(string path, ModelCompile importType, bool phantomFix, bool h2SelectionLogic, bool renderPRT, bool FPAnim, string characterFPPath, string weaponFPPath,
Note to self: Open an issue for reworking how arguments are passed to some of these functions.

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            string inPath = BaseDirectory + "\\data\\" + data_file.ToLower().Replace(".ass", ".fbx"); // Jank code, should probably make this safer
This should use ` GetDataDirectory` https://github.com/num0005/Osoyoos-Launcher/blob/b470fcc3787d752e418dbd072306f772beb2d2c7/Launcher/ToolkitInterface/H1AToolkit.cs#L45
H3 might get data directory overrides in a future build.

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            if (File.Exists(inPath))
Should this log or display an error message if the path is missing?

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +                string outPath = BaseDirectory + "\\data\\" + data_file;
ditto

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +        }
Maybe make this a record?
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/records

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            string rootDir = BaseDirectory + "\\data\\" + path;
same data directory thing.

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +                    string outPath = rootDir + "\\" + (all.Name.ToLower().Replace(".all.fbx", ".jms"));
No need to change this but if this needs the ToLower please add a comment explaining why so no-one removes it.

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            }
GetFiles supports a search pattern
https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.getfiles?view=net-6.0#System_IO_Directory_GetFiles_System_String_System_String_
Should simplify the code.

2022-01-06 04:27 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +                    /* Copy x.all.fbx output if it exists */
Is this why the output path above was normalized to lowercase? Why can't the file be outputted directly to the final directory instead of being copied over afterwards?

2022-01-06 21:36 UTC, infernoplus commented
> I think you could move the implementation to a separate static class or something like that and use the interfaces setup for FBX to make it work for all games. Maybe there is a more natural way to do that in C# just the best thing I can think of right now. Really wish C# had multiple inheritance.

Moved it to it's own class and added support for all games. 
Someone else should test the support for the other games because I don't have them installed. I just looked at the wiki for differences in the folder names and commands. Hopefully I got it all right haha.

2022-01-06 22:31 UTC, num0005 approved these changes
The code seems fine, someone just needs to test it. @General-101 when you have time could you take a look at whatever it actually works?

2022-01-06 23:11 UTC, infernoplus commented
Just found an odd issue with tool.exe in Halo 3 at least that I need to address. Made a post here about it. Gonna write a util to solve this. If you get a chance can either of you confirm this bug exists in Halo 1/2 tool?

https://steamcommunity.com/app/976730/discussions/3/3120423877859517091/?ctp=5#c3200370471664585592

2022-01-06 23:33 UTC, num0005 commented
That's an interesting bug, will look into it.

2022-01-06 23:35 UTC, num0005 requested changes
The UI needs to be setup to support the AutoFBX for H1A, right now there is no way to enable it. Going to test it to see if works for H2C in a bit but at least the UI works.

2022-01-07 05:50 UTC, infernoplus commented
Went down some rabbit holes and wrote a rather uh... interesting... class that can load an FBX, strip parts out of it, and write it back to file.

It does seem to solve the bug, though I was initially off. It's the physics that are getting copied into the render JMS, not the collision. No idea why.

I'll commit changes with this new stuff soonish.

2022-01-07 09:40 UTC, num0005 commented
> As for the H1A UI, I actually don't know how to add that. What do?

Not actually sure right now that code is a bit convoluted and could use a cleanup, I think it would be fine to handle adding that in a different PR.

2022-01-07 22:38 UTC, infernoplus commented
Heh, fixed the function names. Trying to find an api to read & write FBX left me pretty tilted.

As for writing binary vs ascii, I found that the binary doesn't always play nice on export so I'm using ascii. The ascii file is temporary though and is automatically deleted after compiling. It only exists on the drive for a few moments.

Reading binary is fine though, writing just doesn't work for whatever reason.

And on the subject of that, I have an exception catch on the fbx strip code, but no actual logging. How should I handle logging for warnings/errors?

2022-01-08 05:21 UTC, num0005 commented
I don't think logging is setup yet but just use `Trace` https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.trace.traceerror?view=net-6.0
When it gets setup it will use it too.

2022-01-08 05:29 UTC, num0005 approved these changes
LGTM

2022-01-09 18:54 UTC, merged