Fixed broken H3 ALL model import option
num0005/Osoyoos-Launcher pull request #48
Opened 2023-03-31 13:49 UTC by Pepper-Man

Noticed that using the "all" option for model imports in H3 has been broken since [this commit](https://github.com/num0005/Osoyoos-Launcher/commit/9c38ee2b5924c7fcf0fc6526a823fdd989bf698f#diff-14149d47a4393e090ee06a15610f4a6f7e01256cc67c9e137ee7d0e253d810d5) (H3Toolkit.cs, line 181-244) by General, when he refactored the model import types section it failed to account for multiple options and would try passing all the separate tool commands as a single argument.

This is a fairly straightforward fix for this, I simply added a check for "all" being selected and then run each command one by one as it used to. I also slightly refactored the section into separate functions to avoid code repetition.

2023-03-31 22:27 UTC, num0005 approved these changes
preliminarily approval, will take another look at this later

2023-04-04 23:16 UTC, num0005 requested changes
this code was pretty badly broken in 9c38ee2 but this is not the way to fix this. I like the refactor thing you did, I don't think it was strictly needed but it's always nice to break up a big function. 

Keep the refactor but change the way tool is invoked and get rid of the special case for all flags being set unless there is a very good reason for it.

This code uses a [bit field ](https://en.wikipedia.org/wiki/Bit_field) specifically so it can handle any combination of imports.

2023-04-04 23:16 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +
I'm not sure I understand what you are doing here, should this not be handled by the if statements below?

2023-04-04 23:16 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +                args = ImportCollision(path);
also not sure I understand this change, it seems to just break things further/complicate the code.

2023-04-04 23:16 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +
To clarify the intent of the code, `importType` is a bitset, you are meant to be able to pass any combination of imports to this function and it should handle it correctly.

2023-04-04 23:16 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +                args = ImportCollision(path);
basically instead of this weird `args` variable you should just build the arguments and run tool separately within each if statement block.

2023-04-04 23:16 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
>              await RunTool(ToolType.Tool, args, true);
this shouldn't be here, it should instead be within each if-statement block.

2023-04-04 23:18 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +
also don't try to "reuse" args like that, it's not how C# works. The `clear` invocation will not do anything useful. You also don't need to store the args in a temporary variable.

2023-04-06 17:25 UTC, num0005 approved these changes
Code looks fine, did you test it works okay?

2023-04-06 18:05 UTC, Pepper-Man commented
Yes, all works as expected when testing all the combinations of imports etc

2023-04-06 19:31 UTC, merged