ManagedBlam Support: New bitmap automatic compression and override settings, migrated janky ShaderGen code to MB
num0005/Osoyoos-Launcher pull request #56
Opened 2024-06-19 21:01 UTC by Pepper-Man

2024-06-23 01:21 UTC, num0005 requested changes
some feedback.

Would it be possible to bundle the tool with the executable in some smarter way? Was thinking could embed it as a resource and automatically extract it to either a temporary folder in appdata (saved in config to avoid making a mess) or just extract it to the toolkit `bin` folder on first use after any update.

Additionally, it seems like the shader stuff worked fine before, and the new code doesn't seem to really meaningfully improve it, would rather use the old system for now since it just worked. No need to overcomplicate things.

2024-06-23 01:21 UTC, num0005 commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                int startIndex = bitmap_full.IndexOf("tags\\");
what if there is multiple folders called "tags" in the path? If this was modern dotnet would suggest `Path.GetRelativePath`, but that isn't supported in .net framework, but I see at least one backport of it on gist https://gist.github.com/antonKrouglov/07ccc117cb8c30ad8994446a86c062e5

2024-06-23 01:21 UTC, num0005 commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                string bitmap_path = bitmap_full.Substring(startIndex + 5).Replace(".bitmap", "");
pretty sure at least stripping the extension can be done using `Path` even on .net 4.8

2024-06-23 01:21 UTC, num0005 commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                    tagFile.Save();
considering we seem to be modifying the bitmap the function name is a bit misleading.

2024-06-23 01:21 UTC, num0005 commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                    flags.RawValue = 1;
some of this code seems repetitive, maybe add a wrapper around the bitmap tag and implement setters (and maybe getters?) for these properties?

2024-06-23 01:21 UTC, num0005 commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                    flags.RawValue = 1;
Having multiple places with the same magic string that's required to select a field just feels a bit nasty.

2024-06-23 01:21 UTC, num0005 commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                int startIndex = bitmap_full.IndexOf("tags\\");
this file name to tag name translation is also duplicate and could be put into a method.

2024-06-23 01:21 UTC, num0005 commented on OsoyoosMB/OsoyoosMB.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Bungie", "..\Bungie\Bungie.csproj", "{0B848332-9F77-4DB4-9394-938250668580}"
also is there any reason for a second solution file?

2024-06-23 01:21 UTC, num0005 commented on README.md
> +0. Download and install the [.NET 6 Desktop Runtime x64](https://dotnet.microsoft.com/download/dotnet/6.0/runtime). It is *very* important that you download the **64-bit** **Desktop** runtime, otherw
thanks for updating that!

2024-06-23 01:21 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +
so the point of this is to get the root path for the EK? If you need that please use the tool paths to determine it, not the data path.

2024-06-23 01:21 UTC, num0005 commented on Launcher/Utility/ManagedBlam.cs
> +            string exe_path = Path.Combine(ek_path, @"bin\OsoyoosMB.exe");
arguably this should be a new tool path not just hardcoded, would make it easier when debugging, etc. Could be a future improvement.

2024-06-23 01:21 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +
considering the context the most logical thing would be to use the path to tool.exe

2024-06-23 13:12 UTC, Pepper-Man commented on OsoyoosMB/OsoyoosMB.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Bungie", "..\Bungie\Bungie.csproj", "{0B848332-9F77-4DB4-9394-938250668580}"
"Bungie" was the original name of the first iteration of the reference assembly, I deleted it after generating the reference assembly with refasmer but looks like this ref got left behind, will be removed

2024-06-23 13:12 UTC, Pepper-Man commented on Launcher/MainWindow.xaml.cs
> +
Nothing, accidentally created, will be removed

2024-06-23 13:40 UTC, Pepper-Man commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                else
ShaderGenerator function is now gone due to reverting back to non-MB code for shader stuff. I've still separated things out for better readability and expansion.
Argument parsing here is always going to be a bit iffy because of how it can only pass strings to the second exe unfortunately

2024-06-23 13:42 UTC, Pepper-Man commented on OsoyoosMB/OsoyoosMB/Program.cs
> +            string[] non_diffuse_suffixes = {
Leftover from a previous method of checking suffixes, will be removed

2024-06-23 14:39 UTC, Pepper-Man commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                int startIndex = bitmap_full.IndexOf("tags\\");
Fixed using that backport

2024-06-23 14:39 UTC, Pepper-Man commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                string bitmap_path = bitmap_full.Substring(startIndex + 5).Replace(".bitmap", "");
Fixed

2024-06-23 14:40 UTC, Pepper-Man commented on OsoyoosMB/OsoyoosMB/Program.cs
> +                    tagFile.Save();
Function name changed when separated

2024-06-23 14:43 UTC, Pepper-Man commented on OsoyoosMB/ref/ManagedBlam.dll
Added your wording to README.md

2024-06-23 16:30 UTC, Pepper-Man commented on OsoyoosMB/OsoyoosMB/Program.cs
> +            int compress_value = comp_mapping[compression_type];
Done, combobox now uses an enum

2024-06-23 16:44 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            }
actually can just replace this with `BaseDirectory`

2024-06-23 16:44 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            bool MB_success = ManagedBlam.RunMBBitmaps(ek_path, path, compression);
```suggestion
            bool MB_success = ManagedBlam.RunMBBitmaps(BaseDirectory, path, compression);
```

2024-06-23 16:44 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +
```suggestion
```

2024-06-23 16:44 UTC, num0005 commented on Launcher/ToolkitLauncher.csproj
> -    <EmbeddedResource Include="Resources\LicenseInfoFull.txt" />
what happened here? I don't see why this file was changed at all.

2024-06-23 18:39 UTC, num0005 commented on Launcher/ToolkitLauncher.csproj
> +	<None Remove="Resources\LicenseInfoFull.txt" />
this doesn't resolve the issue, can you please just undo all changes to this file? Just copy over the current version from the repo.

2024-06-23 18:42 UTC, num0005 commented
Looks okay now apart from the accidental changes to [Launcher/ToolkitLauncher.csproj](https://github.com/num0005/Osoyoos-Launcher/pull/56/files#diff-affd02094dc7320b9e19c346e8eb3aea3b9bd83084ae2e077b68372708b93ac9) and having two solution files. Should be able to add the 4.8 project to the existing solution file and delete the extra solution file.

2024-06-23 21:31 UTC, Pepper-Man commented
> Looks okay now apart from the accidental changes to [Launcher/ToolkitLauncher.csproj](https://github.com/num0005/Osoyoos-Launcher/pull/56/files#diff-affd02094dc7320b9e19c346e8eb3aea3b9bd83084ae2e077b68372708b93ac9) and having two solution files. Should be able to add the 4.8 project to the existing solution file and delete the extra solution file.

Reverted those changes
Will try to merge it, but when I tried having it under the same solution last time (a test version before I made the pull request) managedblam simply refused to run correctly even with everything else set up correctly

2024-06-24 13:09 UTC, num0005 approved these changes
seems fine now, could use some more abstraction on the MB helper but that can be a future improvement.

2024-06-24 13:09 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            bool MB_success = ManagedBlam.RunMBBitmaps(BaseDirectory, path, compression);
q, couldn't this be run before importing the bitmaps and generate like dummy bitmaps?

2024-06-24 13:36 UTC, Pepper-Man commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            bool MB_success = ManagedBlam.RunMBBitmaps(BaseDirectory, path, compression);
perhaps, i can try that

2024-06-24 14:14 UTC, merged