Add support for automatic repair (rebuilding) of custom FMOD banks
num0005/Osoyoos-Launcher pull request #67
Opened 2024-11-26 14:24 UTC by Pepper-Man

As per Kashiiera's findings ([c20 PR](https://github.com/Sigmmma/c20/pull/237)) ([Discord Post](https://discord.com/channels/615301822474878977/1309504074869116969))

2024-11-26 18:42 UTC, num0005 reviewed
seems mostly fine

2024-11-26 18:42 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            // Remove old .csv so we can very it was generated correctly later
is the reports folder just dumped into the working directory of tool/tool_fast?

2024-11-26 18:42 UTC, num0005 commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            }
why would any of the code involved throw? this catch seems unnecessary and will prevent global error reporting code from seeing the error.

2024-11-26 18:42 UTC, num0005 commented on Launcher/UIHelpers.cs
> +        public object[] ConvertBack(object value, Type[] targetTypes, object parameter, CultureInfo culture)
remove this method and make the class inherit from `OneWayMultiValueConverter`

2024-11-26 19:37 UTC, Pepper-Man commented on Launcher/ToolkitInterface/H3Toolkit.cs
> +            // Remove old .csv so we can very it was generated correctly later
yes, for example if you copy `tool.exe` to a random folder along with `libfbxsdk.dll`, open CMD in that folder and just type `tool` to get it to dump the list of possible verbs, it will create a reports folder alongside itself for future use

2024-11-26 22:32 UTC, Pepper-Man commented
Last commit (77fd921eac6b7ee28f9a0e9d84105797fa528f50) fixes a UI bug that have been annoying me for a while
Namely, the "Compression Type" label not being anchored correctly so it doesn't offset from the combobox correctly when the window is resized. Also, I centred the text in the compression and type comboboxes since it was weirdly high before

Before:
![pre-fix-1](https://github.com/user-attachments/assets/9fd6b978-a282-48a9-9e0e-5044ec06e24a)
![pre-fix-2](https://github.com/user-attachments/assets/af41da14-9767-45c7-80ff-55d0fc00390d)

After:
![post-fix-1](https://github.com/user-attachments/assets/1e10f854-a1a0-4513-9aad-093d80a3a9fc)
![post-fix-2](https://github.com/user-attachments/assets/47c48334-1776-4171-87d4-ac541388ecbe)

2024-11-26 22:47 UTC, Pepper-Man commented
May as well sort the others whilst I'm at it, lines up better with other text now:
**Before:**
![pre-fix](https://github.com/user-attachments/assets/f39243d8-c810-4937-be44-97827e6ceade)

**After:**
![post-fix](https://github.com/user-attachments/assets/4519ae5f-c0d8-471e-b11b-3a0494988c6f)

2024-11-27 09:32 UTC, num0005 requested changes

2024-11-27 09:41 UTC, num0005 commented
Looks good apart from that one thing

2024-11-27 17:33 UTC, num0005 commented
I think there is an aka.ms URL that actually points to the latest version at any given time

2024-11-27 17:33 UTC, merged